import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState, useEffect } from 'react';
export default function Home() {
  const [messages, setMessages] = useState([]);
  const [currentUser, setCurrentUser] = useState('');

  function solicitar() {
    const response = fetch(`https://script.google.com/macros/s/AKfycbw_MHgPKyOdX61wSh9b1olLU04cd3ioH8pU1fQPdxE04wGpwms6mvJ5a6Sj0q3RrGIX/exec?sala=${'Geral'}`);
    response.then(res => res.json()).then(data => setMessages(data));
    const messageContainer = document.querySelector('.message-container');
    messageContainer.scrollTop = messageContainer.scrollHeight
    const mynameInput = document.querySelector('.myname-input');
    setCurrentUser(mynameInput.value);
  }

  useEffect(() => {
    const intervalId = setInterval(solicitar, 1000);
    return () => clearInterval(intervalId);
  }, []);

  function handleSendMessage() {
    const mynameInput = document.querySelector('.myname-input');
    const messageInput = document.querySelector('.message-input');
    const salaInput = document.querySelector('.sala-input');
    const error = document.querySelector('.error-container');

    if (mynameInput.value == '') {
      error.innerHTML = 'Informe um Nick';
    } else if (messageInput.value == '') {
      error.innerHTML = 'Informe uma mensagem';
    } else {
      const newMessage = messageInput.value;
      let user = mynameInput.value;
      let msg = newMessage;
      let room = salaInput.value;
      const formId = '1FAIpQLSfQutm0b9ZB8hfebHoPCDp9zxemvr--8up_Xz8zPqIzo4kn0Q';
      const url = `https://docs.google.com/forms/u/0/d/e/${formId}/formResponse`;
      const params = new URLSearchParams();
      params.append('entry.228090609', user);
      params.append('entry.2025985546', msg);
      params.append('entry.1292555410', room)

      const options = {
        method: 'POST',
        body: params,
        mode: 'no-cors',
      };
      fetch(url, options);
      messageInput.value = '';
      error.innerHTML = '';
    }
  }
  return (
    <>
      <Head>
        <title>Bate papo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className="myname-container">
          <label>Seu Nick: </label>
          <input type="text" className="myname-input"></input>

          <label>Nome da sala: </label>
          <input type="text" className="sala-input" value="Geral"></input>

          <label>Chave da sala: </label>
          <input type="text" className="chave-input"></input>
        </div>

        <div className="message-container">
          {messages.map((message, index) => (
            <div key={index} className={`message ${message.user === currentUser ? 'you-message' : ''}`}>
              {`${message.user === currentUser ? 'You' : message.user}: ${message.message}`}
            </div>
          ))}
        </div>
        <div className="sendmessage-container">
          <input type="text" className="message-input"></input>
          <button onClick={handleSendMessage}>Enviar</button>
        </div>
        <div className="error-container"></div>
      </main>
    </>
  );
}
